# Generated by Django 4.1.4 on 2023-06-13 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_avilable',
            new_name='is_available',
        ),
    ]
